Fixed Gradle wrapper
Regenerated the Gradle wrapper using "gradle wrapper"
and granted execute permissions to the resulting gradlew
file to allow running "./gradlew build" in this project.

Prior to this fix, "./gradlew build" failed with the
error:

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

while "gradle build" worked without errors.